### ISSUE TITLE
Use simple *.js files.

### ISSUE THREAD

**Issue by mozi22** [alexdavid/exprestive#71]
Hi, I would just like to know if I could use *.js files instead of *.coffee files ? If yes, can you shed some light on how can i do that.

**Comment by alexdavid** [comment]
It is possible to use `*.js` files. I originally wrote all of the examples in coffeescript because the verbosity of javascript made using exprestive not very readable. However, since ES6 has all of its new syntactic sugar [I've opened a pull request](https://github.com/alexdavid/exprestive/pull/70) to convert all of the examples to es6 javascript.

[Check out the updated read me here](https://github.com/alexdavid/exprestive/blob/af0d5c5678303439a9610be9d552250da16ad360/README.md)

**Comment by mozi22** [comment]
thanks, that helped
