### ISSUE TITLE
adding middleware on a per-scope basis

### ISSUE THREAD

**Issue by wgottschalk-RMS** [alexdavid/exprestive#74]
We'd like to be able to scope some middleware functions to authenticate for a group of routes. Right now to do that we would have to add middleware to each controller or break out of exprestive to run middleware for a given set of scoped routes.

I'd like to be able to do something like this:

```
module.exports = ({ GET, scopeWithMiddleware }) => {
  scopeWithMiddleware('/api', {to: 'auth#validate'},  () => {
    GET('/users', {to: 'users#index'});
    GET('/widgets', {to: 'widgets#index'});
  });
};
```

maybe there's a way to also handle cases were the middleware is just a function and not a class.  Perhaps just requiring it and handing it off?

```
const validate = require('./middleware/validate')

module.exports = ({ GET, scopeWithMiddleware }) => {
  scopeWithMiddleware('/api', {to: validate},  () => {
    GET('/users', {to: 'users#index'});
    GET('/widgets', {to: 'widgets#index'});
  });
};
```

**Comment by charlierudolph** [comment]
As I mentioned in #75, I don't think we should be putting middleware in the routes file.
A lot of middleware needs to be initialized and thus I think this would be adding complexity to the wrong place. I'd like to suggest a couple alternative solutions. Sorry if you guys have already discussed these.

---

Looking at how rails does things: everything under a scope by default looks for a controller under that namespace. We could so something similar.

``` coffee
# routes.coffee
module.exports = ({ GET, scope }) ->
  scope '/api', ->
    GET '/foo', to: 'something'
```

The foo controller would actually be `ApiSomethingController` instead of just `SomethingController`. You could make a base `ApiController` which you could add middleware too which all other api controllers inherit from. Rails has a way to specify whether or not the scope adds a prefix to its nested routes.

---

We could create the idea of a scope controller. If would be an intermediate controller which can just add middleware.

``` coffee
# routes.coffee
module.exports = ({ GET, scope }) ->
  scope '/api', to: 'api' ->
    GET '/foo', to: 'something'

# controller/api_controller.coffee
module.exports = {
  middleware: someMiddleware
}
```

**Comment by mjhm** [comment]
@charlierudolph 's option (2) seems clearer and less magical to me.
